swagger: '2.0'
info:
  description: Virtual-Exposition-App APIs
  version: 1.0.0
  title: Virtual-Exposition-App APIs
  contact:
    email: mohammed.elsayed.zaki@eye-ltd.com
host: virtual-exposition-app.localhost
basePath: /api/v1
tags:
  - name: Login
    description: /api/v1/apiLogin
  - name: Events
    description: Operation about patients
  - name: Company
    description: Operation about user Company
  - name: EventStand
schemes:
  - http
paths:
  /apiLogin:
    post:
      tags:
        - Login
      summary: login to system
      description: login
      operationId: apiLogin
      consumes: 
        - application/json
      produces: 
        - application/json
      parameters: 
        - in: body
          name: userLoginData
          description: user Login Data
          required: true
          schema:
            $ref: '#/definitions/LoginData'
      responses:
        '201':
          description: successful operation patient created
          schema:
            $ref: '#/definitions/SuccessResponse'
        '401':
          description: Unauthenticated Error
          schema:
            $ref: '#/definitions/ExceptionResponse'
        '422':
          description: The given data failed to pass validation.
          schema:
            $ref: '#/definitions/ExceptionResponse'
        '500':
          description: internal server error
          schema:
            $ref: '#/definitions/ExceptionResponse'
        '501':
          description: not implented
          schema:
            $ref: '#/definitions/ExceptionResponse'
  /events:
    get:
      tags:
        - Events
      summary: Get all events
      description: This can only be done by the logged in user.
      operationId: getAllOpenedEvents
      consumes:
        - application/json
      produces:
        - application/json
      parameters: []
      responses:
        '201':
          description: successful operation patient created
          schema:
            $ref: '#/definitions/SuccessResponse'
        '401':
          description: Unauthenticated Error
          schema:
            $ref: '#/definitions/ExceptionResponse'
        '422':
          description: The given data failed to pass validation.
          schema:
            $ref: '#/definitions/ExceptionResponse'
        '500':
          description: internal server error
          schema:
            $ref: '#/definitions/ExceptionResponse'
        '501':
          description: not implented
          schema:
            $ref: '#/definitions/ExceptionResponse'
  /events/{eventId}/stands:
    get:
      tags:
        - Events
      summary: get patient data
      description: This can only be done by the logged in user.
      operationId: getPatient
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: eventId
          type: integer
          description: event resource id
          required: true
      responses:
        '200':
          description: ok
          schema:
            $ref: '#/definitions/SuccessResponse'
        '401':
          description: Unauthenticated Error
          schema:
            $ref: '#/definitions/ExceptionResponse'
        '500':
          description: internal server error
          schema:
            $ref: '#/definitions/ExceptionResponse'
        '501':
          description: not implented
          schema:
            $ref: '#/definitions/ExceptionResponse'
  /company:
    post:
      tags:
        - Company
      summary: Create new company
      description: This can only be done by the logged in user.
      operationId: createCompany
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: company
          description: Created patient object
          required: true
          schema:
            $ref: '#/definitions/Company'
      security:
        - VirtualExposition_auth: []
      responses:
        '201':
          description: successful operation company created
          schema:
            $ref: '#/definitions/SuccessResponse'
        '401':
          description: Unauthenticated Error
          schema:
            $ref: '#/definitions/ExceptionResponse'
        '422':
          description: The given data failed to pass validation.
          schema:
            $ref: '#/definitions/ExceptionResponse'
        '500':
          description: internal server error
          schema:
            $ref: '#/definitions/ExceptionResponse'
        '501':
          description: not implented
          schema:
            $ref: '#/definitions/ExceptionResponse'
    get:
      tags:
        - Company
      summary: get company data
      description: This can only be done by the logged in user.
      operationId: getCompany
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: patientId
          type: integer
          description: patient id
          required: true
      security:
        - VirtualExposition_auth: []
      responses:
        '200':
          description: ok
          schema:
            $ref: '#/definitions/SuccessResponse'
        '401':
          description: Unauthenticated Error
          schema:
            $ref: '#/definitions/ExceptionResponse'
        '500':
          description: internal server error
          schema:
            $ref: '#/definitions/ExceptionResponse'
        '501':
          description: not implented
          schema:
            $ref: '#/definitions/ExceptionResponse'
  /company/{companyId}:
    put:
      tags:
        - Company
      summary: update company
      description: This can only be done by the logged in user.
      operationId: updateCompany
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: companyData
          description: company data object
          required: true
          schema:
            $ref: '#/definitions/Company'
        - in: path
          name: companyId
          type: integer
          description: company resource id
          required: true
      security:
        - VirtualExposition_auth: []
      responses:
        '202':
          description: successful operation patient updated
          schema:
            $ref: '#/definitions/SuccessResponse'
        '401':
          description: Unauthenticated Error
          schema:
            $ref: '#/definitions/ExceptionResponse'
        '422':
          description: The given data failed to pass validation.
          schema:
            $ref: '#/definitions/ExceptionResponse'
        '500':
          description: internal server error
          schema:
            $ref: '#/definitions/ExceptionResponse'
        '501':
          description: not implented
          schema:
            $ref: '#/definitions/ExceptionResponse'
    delete:
      tags:
        - Company
      summary: delete company data
      description: This can only be done by the logged in user.
      operationId: deleteCompany
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: companyId
          type: integer
          description: company resource id
          required: true
      security:
        - VirtualExposition_auth: []
      responses:
        '200':
          description: company deleted successfully
          schema:
            $ref: '#/definitions/SuccessResponse'
        '401':
          description: Unauthenticated Error
          schema:
            $ref: '#/definitions/ExceptionResponse'
        '500':
          description: internal server error
          schema:
            $ref: '#/definitions/ExceptionResponse'
        '501':
          description: not implented
          schema:
            $ref: '#/definitions/ExceptionResponse'
  /event-stand/{eventStandId}/reserve:
    put:
      tags:
        - EventStand
      summary: update company
      description: This can only be done by the logged in user.
      operationId: reserveEventStand
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: companyData
          description: company data object
          required: true
          schema:
            $ref: '#/definitions/Company'
        - in: path
          name: eventStandId
          type: integer
          description: company resource id
          required: true
      security:
        - VirtualExposition_auth: []
      responses:
        '202':
          description: successful operation patient updated
          schema:
            $ref: '#/definitions/SuccessResponse'
        '401':
          description: Unauthenticated Error
          schema:
            $ref: '#/definitions/ExceptionResponse'
        '422':
          description: The given data failed to pass validation.
          schema:
            $ref: '#/definitions/ExceptionResponse'
        '500':
          description: internal server error
          schema:
            $ref: '#/definitions/ExceptionResponse'
        '501':
          description: not implented
          schema:
            $ref: '#/definitions/ExceptionResponse'
securityDefinitions:
  VirtualExposition_auth:
    type: oauth2
    authorizationUrl: 'http://virtual-exposition-app.localhost/oauth/authorize'
    tokenUrl: 'http://virtual-exposition-app.localhost/oauth/token'
    description: "client_id: 7 </br> client_secret: ivpA8ICLAjhtNcst5mdRvAMiiJLOYRitbA3BQMiY "
    flow: accessCode
    scopes: 
      'write:events': modify events in your account
      'read:events': read your events
definitions:
  ExceptionResponse:
    type: object
    properties:
      code:
        type: integer
        format: int32
      exception:
        type: string
      message:
        type: string
      errors:
        type: string
      trace:
        type: string
  SuccessResponse:
    type: object
    properties:
      success:
        type: boolean
      message:
        type: string
      returnObject:
        type: object
      objectType:
        type: string
  LoginData:
    type: object
    properties:
      grantType:
        type: string
        default: "password"
      clientId:
        type: string
        default: "6"
      clientSecret:
        type: string
        default: "6QS7jQWrxEIA9B2SwC79ZHIKieyzgX5ZiyNaP0x1"
      username: 
        type: string
        default: "cl_user01@eye-ltd.com"
      password: 
        type: string
        default: "cl_user01"
  User:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      email:
        type: string
      username:
        type: string
      password:
        type: string
      remember_token:
        type: string
      hospitalId:
        type: integer
      access_token:
        type: string
      expires_in:
        type: string
      refresh_token:
        type: string
      token_type:
        type: string
  Event:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      location:
        type: string
      lat:
        type: number
        format: double
      lon:
        type: number
        format: double
      img:
        type: string
      startAt:
        type: string
        format: date
        default: '2017-05-02'
      endAt:
        type: string
        format: date
        default: '2017-05-02'
      description:
        type: string
      userId:
        type: integer
  EventStand:
    type: object
    properties:
      id:
        type: integer
      eventId:
        type: integer
      status:
        type: boolean
      price:
        type: number
        format: double
      sqMeters:
        type: string
      description:
        type: string
      logoPos:
        type: string
      userId:
        type: integer
  Company:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      phone:
        type: string
      logoImg:
        type: string
      marketingDocs:
        type: string
      adminName:
        type: string
      adminEmail:
        type: string
      userId:
        type: integer
  UserStandReservation:
    type: object
    properties:
      id:
        type: integer
      eventStandId:
        type: integer
      companyId:
        type: integer
      userId:
        type: integer
